### PR TITLE
Blood Magic Overhaul

### PR DESCRIPTION
**Pull request by chaosvolt**
Obligatory self-PR to get a shot at some feedback.

* Implemented a ritual using the athame as a spell, that generates blood essence when completed. Still creates blood loss at the end, but this is now a side effect instead of part of the process. This makes spamming rags no longer needed to generate blood essence via the athame.
* Likewise reworked the chalice to use this spell setup too, and made the essence gain relative to the athame actually worth dealing damage. As a side benefit, it'll actually mess with stamina like the action
message has always implied.
* Both spells also make use of the long-term side effects that I put together in previous commits, so spamming these items constantly will be problematic in the long run, even with magical healing/lifedrain to offset the potential damage.
* Moved active athames, active chalice, and used chalice to obsolete.json, along with obsoleting the recipes they played a part in.

Two things to note:
1. I would've liked for the spell preview menu to show up like it would for hostile/ally/ground spells, as a layer of idiotproofing to prevent the player accidentally chalice'ing themselves and not realizing it, but it seems that there's no way to do that with self-only spells. I'll have to ask @KorgGenT if they know how that works, but...
2. It looks like it might actually consume the time BEFORE the spell preview menu pops up, so unless there's a way around that then point 1 is a moot point anyway, sadly.
2. Until the skill used for failure rate is un-hardcoded, both chalice and athame have no-fail like item spells usually do. After that, I plan to assign difficulties and test how quickly skill affects fixed-level spells, so that I can partially restore the functionality of the old recipes by making them less practical without a few points of arcana.

### CODE REVIEW

**Comment by KorGgenT** [comment]
How it works is if a spell has a range of 0 or a valid Target of none then
there is no spell preview it just cast it from the spell-casting menu

**Comment by chaosvolt** [comment]
That's what I found so far, yeah. You can give a self-cast spell a range of 1, but then it'll default the cursor to any adjacent NPC or monster, even though the caster is the only valid target. And it still eats up 10-15 minutes of time beforehand, it seems? I think...

It's not really a priority since BOTH items have multiple use actions, so there's always at least one keypress stopping the player from accidentally performing the ritual, but I was partly hoping to use the preview to use the spell description as space to elaborate on what the ritual does, and in the case of the chalice make it more clear to the player that they're about to eat 10 damage square in the chest (to be fair though, the chalice pre-overhaul was already schmuck bait incarnate and ALSO had nothing else to prevent the player from accidentally committing ritual suicide).

**Comment by KorGgenT** [comment]
As soon as you cast the spell your moves are taken up via the activity.
Even if it's a spell that you choose a Target your moves are used up before
you choose the target

**Comment by chaosvolt** [comment]
Ah yeah, that's what I thought happened when I tried giving it range to force the preview menu, yeah. In that case no worries, it still has a reasonable degree of buffer space to prevent accidental usage. I might I guess add the spell description to the item description past a newline, that should work.

Unrelated thing, being able to name a spellcast use action in the item action menu (like what transform allows) would be handy, but understandable if that's not on the todo list. Hoping recent stuff has gone well?

**Pull request merged**
