### PR TITLE
Prepartion for itemgroup overhaul in DDA version

### PR DESCRIPTION
**Pull request by chaosvolt**
Setting aside a branch to have the override itemgroups in the DDA version already prepped for if https://github.com/CleverRaven/Cataclysm-DDA/pull/56469 is merged. Gonna have to do similar for other mods I'm involved in maintaining, but this is a good start for getting used to the new format (also easier as I'm fairly certain this is the only mod I'm involved in that has vanilla-override itemgroups actually set aside separate from new groups).

Closes https://github.com/chaosvolt/cdda-arcana-mod/issues/246

Important question for @anothersimulacrum about the functionality here though: how does this affect mod-intercompatibility itemgroups? Basically, suppose you have an itemgroup normally used by Mod A, and Mod B adds items that would logically belong in Mod A's itemgroups. Under normal circumstances it does not matter if you load Mod B before Mod A, or load Mod B without A, but will that still apply here?

I would logically except to see this in both Aftershock and CRT Expansion for example, since both focus on sci-fi content. Arcana meanwhile is an example that adds content to itemgroups that normally exist in Magiclysm and Cataclysm++.

This is one of the only cases of JSON behavior where it's actually easy to make two mods interact without a third patchmod having to exist, and normally self-copy-from can't handle existing without its intended source being defined elsewhere. Losing this feature would be a MASSIVE drop in utility.

### CODE REVIEW

**Comment by anothersimulacrum** [comment]
> Important question for @anothersimulacrum about the functionality here though: how does this affect mod-intercompatibility itemgroups? Basically, suppose you have an itemgroup normally used by Mod A, and Mod B adds items that would logically belong in Mod A's itemgroups. Under normal circumstances it does not matter if you load Mod B before Mod A, or load Mod B without A, but will that still apply here?

I answered in the relevant issue, but I will expand a little. This is the type of issue for which a mod loaded after both parent mods has been loaded is the 'correct' solution. DDA does not make that very user friendly at the moment, but that doesn't need to be the case.

**Comment by chaosvolt** [comment]
Ah, thank you for the responses. I'll go ahead and move the follow-up questions here then.

> If both itemgroups act as though they are extending an existing itemgroup, it will work.

I see, would it still work if you only use one of the relevant mods? So to use an Arcana-specific example, if you used Arcana but not Magiclysm, would it care that this is citing an itemgroup that currently doesn't have a non-self-copied entry?
```
  {
    "type": "item_group",
    "id": "magic_shop_books",
    "copy-from": "magic_shop_books",
    "//": "Additions to magic shop itemgroups are for automatic compatibility with Magiclysm.  General assumption is only the non-faction books were traded around enough for the non-arcanist magical community to start collecting samples.  Todo: remember magic_CBM itemgroup for when magitech is added to arcana.",
    "extend": {
      "items": [ [ "book_potioncraft", 25 ], [ "book_scrollcraft", 15 ], [ "book_summoning", 10 ], [ "book_syncretism", 5 ] ]
    }
  },
```

> and so load order would be the appropriate way for that problem to be addressed.

I see. Right now itemgroup mod-incompatibility is load order agnostic, it only cares on the "time to actually spawn some items" end whether the group exists or not.

I suppose this would be a good excuse to finally make official patchmods (monsterdrop injections can already be a pain without that, just to use an example relevant to Arcana) but more ways to make mods interact smoothly without extra steps is always an improvement, since that simplifies things for the end user.

**Comment by anothersimulacrum** [comment]
It would not care.

**Comment by chaosvolt** [comment]
Ah, nice. Hopefully things work out then, and thank you for the info. I still need to get time and energy to see about patchmod content one of these days anyway, just lot to juggle these days.

**Comment by chaosvolt** [comment]
Downloaded the branch for the PR, dumped this branch of the mod in it, compiled and tested a fitting itemgroup, `magic_CBM` in this case. First with just Arcana on the mod list:
image

Next, with Arcana followed by Magiclysm on the modlist:
image

So that's actually a different problem than I first thought might happen, hmm. Loading only one mod will work fine but since an itemgroup is full-override by default that means the "patchmods are needed to prevent breakage" thing is already in play.

**Comment by chaosvolt** [comment]
Going to need to prepare updates for my other mods and Cata++ later, will be out and about today.

**Pull request merged**
