### PR TITLE
[CR] Prettification of the README.md

### PR DESCRIPTION
**Pull request by Rod995**
I'll need a few hints to what looks good and what needs to be changed @chaosvolt.

### CODE REVIEW

**Comment by chaosvolt** [comment]
> commit name: you shouldn't see this
> does so anyway

:3

Looks good overall, a couple smol things I think I'll inject into this maybe, to add to consistency.

**Comment by chaosvolt** [comment]
Oof, the only problem is the style is all over the place,changing nearly every section. D:

**Comment by Rod995** [comment]
Mhmm.
You gotta tell me what looks good, ya demon!

**Comment by chaosvolt** [comment]
Ack. One second, internet bein' oofed by rain.

**Pull request merged**
