### PR TITLE
Adds a new talisman item, pet properties for summoned monsters

### PR DESCRIPTION
**Pull request by chaosvolt**
Self-PRing mainly because I knew this would take me a bit of commit-bouncing before it was ready.

* Added air talismans, which are intended to be used to give pet functions to summoned monsters, to make them more useful if desired. This officially rounds out the talisman's elemental theming, and the use of 
* Also gave certain added pet functions to specific summoned monsters. Dark wyrms, jabberwocks, things, and yuggs can all be mounted. They've been made faster but still don't make ideal mounts, and are even worse hauling animals. Their main advantage is being much stronger than mundane mounts, better able to carry their rider.
* For flavor reasons, skeletal dogs and krecks can be played with. :3

Some considerations and complications:
* There's no real vertical space left as far as pack animals go, because engine power calculation are rigged in such a way that horses are both the fastest option AND the best hauler. There wouldn't even be room to allow oxen to be better at carrying loads, let alone letting you strap a giant hulking flesh golem to a wagon and expecting them to actually carry heavy loads.
* I'd genuinely advise not trying to use summoned creatures to haul wagons, because the reported safe speed is bollocks. Vehicle menu will display a value based off engine power, but actual safe speed is fixed at monster speed (which will generally be lower than the alleged safe speed).
* I found out that you CAN hitch friendly monsters to carts even if they aren't pets, but you don't have the ability to unhitch them.
* Pet effect is the only method to make invalid monsters permit accessing the pet menu, since taming items aren't JSONized. It's an interesting workaround, but you can't make the effect actually permanent. I was gonna do a year and a day for the obvious symbolism, but that seems to generate an overflow error. 200 days is a reasonable long-term value that doesn't run into this, however.
* I'd advise against letting monsters carry your bags, as it doesn't seem to actually display weight/volume limits, nor do they let you take items out without removing the chosen storage item entirely. Also it's a bit silly to allow light creatures like vortices to carry bags for you, but you can already give backpacks to chickens or other absurdities so I'm not concerned by that.
* Yes, you can in fact waste this on summoned monsters that're going to vanish due to being summoned by non-permanent summoning spells, though that is potentially still situationally useful. It also can be wasted by casting it then canceling, much to my annoyance. I might make it slightly more idiotproof (and less wasteful) via making it an AoE effect instead, with enough radius to make it unlikely that your intended pal will wander off.
* I plan to add some options for armor too, likely to To Master The Unknown.

### CODE REVIEW

**Comment by chaosvolt** [comment]
Welp...huh. I might want to ask @korggent if they know anything about this. Finding I'd found out: you can cast this on yourself despite the spell itself being marked as only allies, not self. Also applies if one sets it to an AoE effect, so I guess that's out. :/

**Comment by KorGgenT** [comment]
You probably have an old build then, I fixed the thing that targets self when allies are valid

**Comment by chaosvolt** [comment]
Ah! That might be the cause. I'll update build and test it in a bit. Thank you, that should enable setting it to an AoE effect to make it a bit easier to use on summoned critters.

**Comment by chaosvolt** [comment]
Ahah, that looks like it'd explain it. I knew I'd updated build recently, but that was on the desktop, not the laptop. Sorry for pestering you about it here. I wish I'd had the chance to friend you before you left the server so I could just bounce ideas off you in DMs instead of having to ping you here or in your repo.

**Pull request merged**
