### PR TITLE
Fix fuel energy consumption in DDA version

### PR DESCRIPTION
**Pull request by a666**
Due to https://github.com/CleverRaven/Cataclysm-DDA/pull/60607

### CODE REVIEW

**Comment by chaosvolt** [comment]
So, quick question: what level of volume is material fuel value supposed to be for now? Before I was fairly certain it was supposed to be kJ per individual unit of fuel, but the values from the DDA PR would be off by a factor of 1000 if so. Evidently the PR references MJ/L instead, if this is what the energy values are supposed to be now the given values for regular essence and blood essence will be incorrect.

If it is intended to be MJ/L and not an error on the part of the source PR's OP, correct values will be "8000 kJ" for blood essence (as each unit is 40 kJ and 5 mL), and "12000 kJ" for regular essence (as each unit is 120 kJ and 10 mL).

**Comment by a666** [comment]
Ah, the eternal question of DDA PRs: Does it work as it should?

Want to wait until there's more eyes on that PR?

**Comment by chaosvolt** [comment]
When I get home I'll grab the branch to test, just in case they did do something wacky.

**Comment by chaosvolt** [comment]
Finally remembered to test this, looks like the results would indeed need an adjustment. I can do that myself right quick, then merge after double-checking some other stuff.
image

**Comment by chaosvolt** [comment]
Welp, should've actually tested to make sure the actual results would be even remotely close to what the refuel menu actually says, but looks like @Hirmuolio got some part of the math WILDLY wrong at some point. This was after draining one each of all three essence items, which in the 100% efficient essence surge CBM SHOULD have provided a total of 164 kJ:
image

If it'd say 16 joules then it would at least be off by a factor of 1000, but 24 joules indicates it's even more fucked up than that. Just to be sure I tested the Battery System CBM, and...yep, something is fucked here:
image

**Comment by chaosvolt** [comment]
Ah, looks like it should be fixed in https://github.com/CleverRaven/Cataclysm-DDA/pull/60876 and just hadn't made it into the next available build, but I'll still have to retest to make sure everything's working as intended.

**Comment by a666** [comment]
Outstanding work!

**Pull request merged**
