### PR TITLE
Alchemical ideas

### PR DESCRIPTION
**Pull request by chaosvolt**
* Two items notably suggested by @TriffidKing a while back: carmine vulnerary and citrine incense. Both are essentially combinations of two potions to obtain a specific effect. The former entails applying the effect topically to gain healing (initially weaker than a water talisman, but scales up to heal more with first aid skill) along with localized treatment of bleeding and bites, with more limited secondary effects and painkilling in-between red and black potion. The latter is mainly for mitigating fatigue directly (bypassing stims), mainly of use for spellcasters.
* Blood effigy, a mutation item designed as the pre-threshhold equivalent to the sacramental heart. Currently also only enables access to the non-spell mutations (also making it more useful if given to NPCs), but I'm tempted to give it the risk of adding unrelated mutations if I can think of anything interesting (the long-standing "can't copy-from to override mutations" thing means I can't assign it any vanilla mutations).
* Alchemical recipes for making silver and gold, referencing a description of allegedly successful projection in De Natura Vitae Eternae (with a little essence boost). I'm tempted to make the recipe a bit more complex but unsure what would be good thematically.
* Updated which mutations are needed for Rite of Blood.
* A few assorted rebalances and tweaks to potion recipes, notably expanding some alternatives for crafting.

### CODE REVIEW

**Comment by adamkad1** [comment]
mana potion, yay

**Comment by chaosvolt** [comment]
> mana potion, yay

Heh, close as we can get with what the mutation system allows, effectively.

**Comment by Maddremor** [comment]
Haven't `copy-from` been fixed for mutations though?

**Comment by chaosvolt** [comment]
> Haven't copy-from been fixed for mutations though?

Last I checked, no. Well, it still doesn't work at least, but during last test it simply failed to edit properly, when back in the day the game would instead freeze up.

**Comment by chaosvolt** [comment]
Oh. I found the problem. The issue got closed without a solution, either because it seemed suggestion-y or because of other shenanigans.

**Pull request merged**
