### PR TITLE
incorruptible sword adjustment

### PR DESCRIPTION
**Pull request by Dan1ss1mo**
Stats adjustment for incorruptible sword.
I changed cutting damage to be the same as tempered arming sword, although i am not sure if if should be higher or not. I also changed material to tempered steel and removed gold as it would negatively affect weapon durability.

### CODE REVIEW

**Comment by chaosvolt** [comment]
It having gold as a submaterial is intentional, it affects what materials can be used to repair, and is consistent with the extensive variety of items using relevant materials as a submaterial. It should be inheriting `STURDY_MELEE` from its parent item to mitigate this, unless they removed that from proper medieval weapons in DDA now.

**Comment by Dan1ss1mo** [comment]
> It having gold as a submaterial is intentional, it affects what materials can be used to repair, and is consistent with the extensive variety of items using relevant materials as a submaterial. It should be inheriting `STURDY_MELEE` from its parent item to mitigate this, unless they removed that from proper medieval weapons in DDA now.

No, it still has sturdy melee. But somewhat recently where was a pr that removed handle material from bladed weapons, as it was affecting chip resistance, so it would probably be the case for gold as well

**Comment by Dan1ss1mo** [comment]
It would probably also be a good idea to add arcana recipe for medium still, so you could easyer maintain you're tempered gear

**Comment by Dan1ss1mo** [comment]
Also, why does it has such high bash compered to other swords decpite being lighter then arming sword?

**Comment by chaosvolt** [comment]
Okay this sounds like a lot of shit I'm going to have to look into and fix myself, it seems.

> No, it still has sturdy melee. But somewhat recently where was a pr that removed handle material from bladed weapons, as it was affecting chip resistance, so it would probably be the case for gold as well

I'll have to overhaul a lot more items it seems, if that's the case. But that sounds like something weird is going on on their end because last I checked swords already didn't have wood as a submaterial, it was only used for polearms and the like where it being part wood was logical.

Also I thought item damage in melee used bash resistance, and chip resist specifically was only for item damage from explosions?

> Also, why does it has such high bash compered to other swords decpite being lighter then arming sword? I did not touched it as twere may be some reasoning behind this that i'm not aware of

It was supposed to be slightly heavier on average than most of the swords you could use to make it, due to the added weight from the decorations, and gained increased bash damage to compensate for that. I guess I'll have to look into this more later, hmm.

**Comment by Dan1ss1mo** [comment]
> Okay this sounds like a lot of shit I'm going to have to look into and fix myself, it seems.
> 
> > No, it still has sturdy melee. But somewhat recently where was a pr that removed handle material from bladed weapons, as it was affecting chip resistance, so it would probably be the case for gold as well
> 
> I'll have to overhaul a lot more items it seems, if that's the case. But that sounds like something weird is going on on their end because last I checked swords already didn't have wood as a submaterial, it was only used for polearms and the like where it being part wood was logical.
> 
> Also I thought item damage in melee used bash resistance, and chip resist specifically was only for item damage from explosions?
> 
> > Also, why does it has such high bash compered to other swords decpite being lighter then arming sword? I did not touched it as twere may be some reasoning behind this that i'm not aware of
> 
> It was supposed to be slightly heavier on average than most of the swords you could use to make it, due to the added weight from the decorations, and gained increased bash damage to compensate for that. I guess I'll have to look into this more later, hmm.

i think golden part is small enough to not affect weapon performance much any way, so repairing it with gold would make as much sense as repairing handle part with leather

**Pull request merged**
