### PR TITLE
The "Urban Awakening" Update

### PR DESCRIPTION
**Pull request by chaosvolt**
As usual, self-PRing for the sake of feedback. Closes https://github.com/chaosvolt/cdda-arcana-mod/issues/42

Also closes https://github.com/chaosvolt/cdda-arcana-mod/issues/45

* A city-focused scenario, Urban Awakening. In it players can start in an arcanist basement, cathedral basement, or a basement somewhere much more !!FUN!! instead.
* Figured out how to use `regional_overlay` to make arcanist basements a separate `om_terrain`, enabling the scenario above.
* Two new professions added, specific to the Urban Awakening scenario. Both reference writing concepts from a notable succession game that's given me a lot of Arcana ideas in the past, and thus make their particular inspiration canon in a broad-strokes form.

### CODE REVIEW

**Comment by mding9** [comment]
NICE

**Comment by chaosvolt** [comment]
It's really more because the game tries (and fail) is my guess. Being in the basement there puts you on the edge of town, so it's easy enough to just fall back and gamble on whatever is nearby instead of pushing inwards, with the bulk of the potential challenge (and spoilers) requiring the player to actively pursue not only deeper into the city, but underneath it. :3

That said, the only tenuous connection to arcana right now is the fact some of the monsters down below are reworked to imply a connection to the arcane, making it more of a "just for fun" option and not essential if it turns out to be a bad idea.

**Comment by mding9** [comment]
Does the archeologist fit into the scenario?

**Comment by chaosvolt** [comment]
I was actually tempted to add them to it, as they'd be a natural fit for it. Lab tech or some other science profession would also be interesting lore-wise (and fit my plan of eventually adding an anomalous material lab), but the lab tech seems more geared towards the intended scenarios. However, there was the "arcane researcher" idea suggested in https://github.com/chaosvolt/cdda-arcana-mod/issues/45 that might compliment that.

**Pull request merged**
